#! /bin/bash
if [ -f vol ] ; then rm vol ; fi
if [ -f econf ] ; then rm econf ; fi
if [ -f time_ ] ; then rm time_ ; fi
touch vol
touch econf
touch time_
k=0
for i in `seq 1 $1` ; do
   k=`wc -l vol | awk '{print $1}'`
   grep 'Cell volume :' MD_$i/md.gout.$i  | awk '{ s += $6 } {print $6,s/NR}' >> vol
   grep 'Potential energy  (eV) =' MD_$i/md.gout.$i  | awk -v k=$k '{ s += $5 } {print NR+k,$5,s/NR}' >> econf
   grep '** Time :' MD_$i/md.gout.$i  | awk '{print $4}' >> time_
   let k++
done
paste econf vol > datos.txt
rm vol econf time_
echo "set term postscript eps color enhanced blacktext 'Helvetica,20' ; set o 'v_e.eps' ; set y2tics
plot 'datos.txt' u 1:((\$5/8.0)**(1/3.0)) w l,'datos.txt' u 1:3 axis x1y2 w l" > t
gnuplot < t
gv v_e.eps 
exit 0
